/* eslint-disable @next/next/no-img-element */
import cuid from "cuid";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

type Preview = {
  id: string;
  src: string;
};

const Home: NextPage = () => {
  const [isDragging, setIsDragging] = useState(false);
  const [previews, setPreviews] = useState<Preview[]>([]);
  const upload = trpc.useMutation(["images.upload"]);

  const onDrogFile = async (evt: React.DragEvent) => {
    evt.preventDefault();

    const files = evt.dataTransfer.files;
    if (files.length) {
      const uploadUrls = await upload.mutateAsync({
        slugs: Array.from({ length: files.length }, () => cuid()),
      });
      console.log(uploadUrls)
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const upload = uploadUrls[i];
        if (!file || !upload) throw Error("Invalid file or url");
        const reader = new FileReader();
        reader.onload = (e) => {
          const src = e.target?.result as string;
          setPreviews((prev) => [...prev, { id: upload.slug, src }]);
        };
        reader.readAsDataURL(file);
        const res = await fetch(upload.url, {
          method: "PUT",
          body: file,
        });
        if (!res.ok) throw Error("Failed to upload");
      }
    } else {
      setIsDragging(false);
    }
  };

  return (
    <>
      <Head>
        <title>Tincy Pics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex h-screen transition-colors duration-500 ${
          isDragging ? "bg-blue-500" : "bg-gray-50"
        }`}
      >
        <div className="m-auto flex w-full max-w-sm flex-col">
          <h1
            className={`text-center text-xl font-semibold transition-colors duration-500 ${
              isDragging ? "text-white" : "text-slate-700"
            }`}
          >
            tincy.pics
          </h1>
          <div className="mt-2 flex w-full flex-col rounded bg-white p-2 shadow-lg">
            <div
              className={`flex h-32 w-full flex-col items-center justify-center border-4 border-dashed transition-colors duration-200 ${
                isDragging ? "border-blue-500" : "border-slate-200"
              }`}
              onDragOver={(evt) => {
                evt.preventDefault();
                setIsDragging(
                  evt.dataTransfer.items && evt.dataTransfer.items.length > 0
                );
              }}
              onDrag={(evt) => {
                evt.preventDefault();
              }}
              onDragLeave={(evt) => {
                evt.preventDefault();
                setIsDragging(false);
              }}
              onDrop={onDrogFile}
            >
              <p className="text-center text-slate-700">
                Drag and drop your file
              </p>
            </div>
          </div>
        </div>
        {previews.length > 0 && (
          <div className="absolute top-0 left-0 h-screen w-full animate-fade overflow-y-auto overflow-x-hidden px-16 backdrop-blur-sm backdrop-brightness-50 transition-all">
            {previews.map((preview, i) => (
              <div
                key={preview.id}
                className="mt-[20%] flex h-[80%] w-full flex-col items-center"
              >
                <img className="" src={preview.src} alt="" />
                <div
                  className="mt-12 max-w-md cursor-pointer rounded bg-white p-4 text-slate-700"
                  onClick={() => navigator.clipboard.writeText(`https://i.tincy.pics/${preview.id}`)}
                >
                  https://i.tincy.pics/{preview.id}
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
