/* eslint-disable @next/next/no-img-element */
import cuid from "cuid";
import produce from "immer";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

type Preview = {
  id: string;
  src: string;
  done: boolean;
};

const Home: NextPage = () => {
  const [isDragging, setIsDragging] = useState(false);
  const [previews, setPreviews] = useState<Preview[]>([]);
  const upload = trpc.useMutation(["images.upload"]);

  const preventDefaults = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const onDrogFile = async (evt: React.DragEvent) => {
    preventDefaults(evt);

    const files = [...evt.dataTransfer.files].filter((file) =>
      file.type.startsWith("image/")
    );
    if (files.length) {
      setIsDragging(true)
      const slugs = Array.from({ length: files.length }, () => cuid());
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const reader = new FileReader();
        reader.onload = (e) => {
          const src = e.target?.result as string;
          setPreviews(
            produce((draft) => {
              draft.push({ id: slugs[i], src, done: false });
            })
          );
        };
        reader.readAsDataURL(file);
      }
      const uploadUrls = await upload.mutateAsync({
        slugs,
      });
      console.log(uploadUrls);
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const upload = uploadUrls[i];
        const res = await fetch(upload.url, {
          method: "PUT",
          body: file,
        });
        if (!res.ok) throw Error("Failed to upload");
        setPreviews(
          produce((draft) => {
            const index = draft.findIndex((p) => p.id === slugs[i]);
            draft[index].done = true;
          })
        );
      }
    } else {
      setIsDragging(false);
    }
  };

  return (
    <>
      <Head>
        <title>Tincy Pics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex h-screen transition-colors duration-500 ${
          isDragging ? "bg-blue-500" : "bg-gray-50"
        }`}
        onDrop={onDrogFile}
        onDragOver={preventDefaults}
        onDrag={preventDefaults}
        onDragLeave={preventDefaults}
      >
        <div className="m-auto flex w-full max-w-sm flex-col">
          <h1
            className={`text-center text-xl font-semibold transition-colors duration-500 ${
              isDragging ? "text-white" : "text-slate-700"
            }`}
          >
            tincy.pics
          </h1>
          <div className="mt-2 flex w-full flex-col rounded bg-white p-2 shadow-lg">
            <div
              className={`flex h-32 w-full flex-col items-center justify-center border-4 border-dashed transition-colors duration-200 ${
                isDragging ? "border-blue-500" : "border-slate-200"
              }`}
              onDragOver={(evt) => {
                preventDefaults(evt);
                setIsDragging(
                  evt.dataTransfer.items && evt.dataTransfer.items.length > 0
                );
              }}
              onDragLeave={(evt) => {
                preventDefaults(evt);
                setIsDragging(false);
              }}
            >
              <p className="text-center text-slate-700">
                Drag and drop your file
              </p>
            </div>
          </div>
        </div>
        {previews.length > 0 && (
          <div className="absolute top-0 left-0 h-screen w-full animate-fade overflow-y-auto overflow-x-hidden px-16 backdrop-blur-sm backdrop-brightness-90 transition-all">
            {previews.map((preview, i) => (
              <div
                key={preview.id}
                className="mt-[10vw] flex h-[80vw] w-full flex-col items-center"
              >
                <img className="rounded shadow-xl" src={preview.src} alt="" />
                <div
                  className={`mt-12 max-w-md cursor-pointer rounded p-4 text-slate-700 shadow-xl transition-colors ${
                    preview.done ? "bg-white" : "bg-gray-300"
                  }`}
                  onClick={() =>
                    navigator.clipboard.writeText(
                      `https://i.tincy.pics/${preview.id}`
                    )
                  }
                >
                  https://i.tincy.pics/{preview.id}
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
